# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=64, verbose_name='书名'),
        ),
    ]
