# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180920_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Userdetiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='infi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Userdetiel', unique=True),
        ),
    ]
