# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181130_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(error_messages={}, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='infi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Userdetiel'),
        ),
        migrations.AlterField(
            model_name='userdetiel',
            name='info',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
