# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20181206_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetiel',
            name='info',
            field=models.CharField(max_length=64),
        ),
    ]
