# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20190302_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(upload_to='./static/images/Video/', verbose_name='图片'),
        ),
    ]
